#!/bin/bash
#
# hrmd         Huygens Remote Manager daemon
#
# chkconfig: - 85 15
# description: Huygens Remote Manager daemon
# processname: hrmd
#
### BEGIN INIT INFO
# Provides: hrmd
# Required-Start:
# Description: The HRM Queue Manager daemon
### END INIT INFO
#
# This file is part of the Huygens Remote Manager
# Copyright and license notice: see license.txt

# set the defaul value for the PHP CLI binary:
PHP_CLI="php"

# hrm.conf defines variable HRM_HOME
. /etc/hrm.conf

start() {
    # Is an instance of the Queue Manager already running?
    inst=`ps aux | grep runHuygensRemoteManager.php`;
    if [[ $inst == *"php -q"* ]]
    then
	echo""
	echo "The Queue Manager is already running: I won't start another instance."
        echo "Usage: hrmd {start|stop|restart}" 
        exit
    fi
    
    cd  "$HRM_HOME"/run
        echo Reporting to "$HRM_LOG"/log.txt "$HRM_LOG"/error_log.txt

        cmd="$PHP_CLI -q \"$HRM_HOME\"/run/runHuygensRemoteManager.php 1> \"$HRM_LOG\"/log.txt 2> \"$HRM_LOG\"/error_log.txt &"
	su "$SUSER" -c "$cmd"

	if [ "$?" = 0 ]
	then
		sleep 3
		cmd="pidof php > $HRM_LOG/hrmd.pid"
		su "$SUSER" -c "$cmd"
		echo "Starting HRM daemon...................ok"
	fi
        # This will show if anything went wrong during the start up.
        tail "$HRM_LOG"/log.txt
}


stop() {
	if [ -f "$HRM_LOG"/hrmd.pid ]
	then
		cmd="kill -9 $(cat $HRM_LOG/hrmd.pid | tr '\n' ' ')"
		su "$SUSER" -c "$cmd"
		
		if [ "$?" = 0 ]
		then
			cmd="rm -f $HRM_LOG/hrmd.pid"
			su "$SUSER" -c "$cmd"
			echo "Shutting down HRM daemon..............ok"
		fi
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: hrmd {start|stop|restart}"
esac

